services:
  app:
    image: rest-api-image
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - qdrant
    networks:
      - custom_network
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/${PORT}']
  db:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - custom_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB}', '-h', 'db']
      start_period: 5s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '${QDRANT_PORT}:${QDRANT_PORT}'
    networks:
      - custom_network

volumes:
  postgres_data:
networks:
  custom_network:
